#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

frontmatter_field() {
  local file_path="$1"
  local field_name="$2"

  awk -v field_name="$field_name" '
    NR == 1 && $0 == "---" { in_frontmatter = 1; next }
    in_frontmatter && $0 == "---" { exit }
    in_frontmatter && index($0, field_name ":") == 1 {
      sub("^[^:]+:[[:space:]]*", "", $0)
      print
      exit
    }
  ' "$file_path"
}

build_index() {
  local section_dir="$1"
  local section_title="$2"
  local index_path="${REPO_ROOT}/${section_dir}/index.md"
  local tmp_file
  local entries_file
  local rel_path
  local label
  local description
  local lesson_id
  local sort_key
  local line

  tmp_file="$(mktemp)"
  entries_file="$(mktemp)"
  {
    printf '# %s Index\n\n' "$section_title"
    printf '> Generated by `scripts/rebuild-indexes.sh` on %s\n\n' "$(date '+%Y-%m-%d %H:%M %Z')"
  } > "$tmp_file"

  find "${REPO_ROOT}/${section_dir}" -maxdepth 1 -type f -name '*.md' ! -name 'index.md' | sort | while IFS= read -r file_path; do
    rel_path="./$(basename "$file_path")"
    label="$(frontmatter_field "$file_path" "name")"
    description="$(frontmatter_field "$file_path" "description")"
    lesson_id="$(frontmatter_field "$file_path" "lesson_id")"
    if [ -z "$label" ]; then
      label="$(basename "$file_path" .md)"
    fi
    if [ -n "$lesson_id" ]; then
      label="${lesson_id} — ${label}"
    fi
    if [ -n "$description" ]; then
      line="- [${label}](${rel_path}) — ${description}"
    else
      line="- [${label}](${rel_path})"
    fi

    if [ "$section_dir" = "lessons" ] && [ -n "$lesson_id" ]; then
      lesson_num=$((10#${lesson_id#L}))
      sort_key="0-$(printf '%04d' "$lesson_num")"
    else
      sort_key="1-$(basename "$file_path" .md)"
    fi

    printf '%s\t%s\n' "$sort_key" "$line" >> "$entries_file"
  done

  sort "$entries_file" | cut -f2- >> "$tmp_file"
  rm -f "$entries_file"
  mv "$tmp_file" "$index_path"
}

build_index "lessons" "Lessons"
build_index "projects" "Projects"
build_index "daily" "Daily"
